version: 2
models:
  - name: cust_t
    tests:
     - test_count_check:
        compare_source: source("PUBLIC","CUSTOMER")
        config:
          store_failures: true
    columns:
     - name: cust_key
       tests: 
         - unique:
            config:
              store_failures: true
              schema: STAGING
              alias: cust_duplicate_rec  
         - not_null:
            config:
              store_failures: true 
              severity: error
              error_if: ">10"
              warn_if: ">2"
              schema: STAGING
              alias:  cust_null_rec
  - name: orders_t
    columns:
     - name: order_price
       tests: 
         - test_valid_amount
  - name: part_t
    columns:
     - name: part_retail_price
       tests: 
         - test_valid_amount
  
sources:
  - name: PUBLIC
    database: DEV
    schema: PUBLIC
    tables:
      - name: CUSTOMER
        description: CUSTOMER master data
        columns:
          - name: c_custkey
            description: Provides unique identifer for every customer
            tests:
              - unique
      - name: ORDERS
        description: ORDERS master data
        columns:
          - name: o_orderstatus
            description: Provides the status of the orders
            tests:
             - accepted_values:
                values: ['F','P','O']
      - name: NATION
        description: NATION master data
      - name: REGION
        description: REGION master data
      - name: LINEITEM
        description: Lineitem transactional data
      - name: JOB_CTRL_TBL
        description: Job control table
      - name: PART
        description: Provides the details on parts

  - name: NA
    database: DEV
    schema: NA
    tables:
      - name: NA_CUSTOMERS
      - name: DIM_CUSTOMER
        description: CUSTOMER table for NA region


  - name: EMEA
    database: DEV
    schema: EMEA
    tables:
      - name: DIM_CUSTOMER
        description: CUSTOMER table for EMEA region


  - name: APAC
    database: DEV
    schema: APAC
    tables:
      - name: DIM_CUSTOMER
        description: CUSTOMER table for APAC region
