---
version: 2
models:
  - name: apac_customers
    columns:
      - name: cust_key
        tests:
          - unique
          - not_null
sources:
  - name: PUBLIC
    database: DEV
    schema: PUBLIC
    tables:
      - name: CUSTOMER
        description: CUSTOMER master data
      - name: NATION
        description: NATION master data
      - name: REGION
        description: REGION master data
