---
version: 2
models:
  - name: customers_var
    description: This model is used to load customer realted data of various region to a region specific customer table.
    columns:
      - name: cust_key
        tests:
          - unique
          - not_null
  - name: apac_customers
    columns:
      - name: cust_key
        tests:
          - unique:
              config:
                store_failures: true
                schema: APAC
                alias:  apac_customers_not_null_fail
          - not_null:
              config:
                store_failures: true 
                schema: APAC
                alias:  apac_customers_unique_fail
sources:
  - name: PUBLIC
    database: DEV
    schema: PUBLIC
    tables:
      - name: CUSTOMER
        description: CUSTOMER master data
      - name: NATION
        description: NATION master data
      - name: REGION
        description: REGION master data
      - name: ORDERS
        description: ORDERS master data
  - name: NA
    database: DEV
    schema: NA
    tables:
      - name: CUSTOMER
        description: CUSTOMER table for NA region
  - name: EMEA
    database: DEV
    schema: EMEA
    tables:
      - name: CUSTOMER
        description: CUSTOMER table for EMEA region
  - name: APAC
    database: DEV
    schema: APAC
    tables:
      - name: CUSTOMER
        description: CUSTOMER table for APAC region