---
version: 2
models:
  - name: my_first_dbt_model
    description: A starter dbt model
    columns:
      - name: id
        description: The primary key for this table
        tests:
          - unique
          - not_null
  - name: my_second_dbt_model
    description: A starter dbt model
    columns:
      - name: id
        description: The primary key for this table
        tests:
          - unique
          - not_null
sources:
  - name: PUBLIC
    database: DEV
    schema: PUBLIC
    tables:
      - name: CUSTOMER
        description: CUSTOMER master data
      - name: NATION
        description: NATION master data
      - name: REGION
        description: REGION master data
